version: "3.9"
services:
  mongo:
    image: mongo:6.0
    ports: ["27017:27017"]
    volumes: ["mongo_data:/data/db"]

  app:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongo:27017/franchisesdb
      - MONGODB_DB=franchisesdb
      - PORT=8080
    ports: ["8080:8080"]
    depends_on: [mongo]

volumes:
  mongo_data:
